#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kar_Zarar_Takip_Sistemi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kar_zarar")]
	public partial class KarzararDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSirket(Sirket instance);
    partial void UpdateSirket(Sirket instance);
    partial void DeleteSirket(Sirket instance);
    partial void InsertGelirGider(GelirGider instance);
    partial void UpdateGelirGider(GelirGider instance);
    partial void DeleteGelirGider(GelirGider instance);
    #endregion
		
		public KarzararDataContext() : 
				base(global::Kar_Zarar_Takip_Sistemi.Properties.Settings.Default.kar_zararConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KarzararDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KarzararDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KarzararDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KarzararDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Sirket> Sirkets
		{
			get
			{
				return this.GetTable<Sirket>();
			}
		}
		
		public System.Data.Linq.Table<GelirGider> GelirGiders
		{
			get
			{
				return this.GetTable<GelirGider>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sirket")]
	public partial class Sirket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _isim;
		
		private System.Nullable<int> _sirket_kodu;
		
		private string _telefon;
		
		private string _fax;
		
		private string _eposta;
		
		private string _yetkili_kisi;
		
		private string _adres;
		
		private EntitySet<GelirGider> _GelirGiders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnisimChanging(string value);
    partial void OnisimChanged();
    partial void Onsirket_koduChanging(System.Nullable<int> value);
    partial void Onsirket_koduChanged();
    partial void OntelefonChanging(string value);
    partial void OntelefonChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnepostaChanging(string value);
    partial void OnepostaChanged();
    partial void Onyetkili_kisiChanging(string value);
    partial void Onyetkili_kisiChanged();
    partial void OnadresChanging(string value);
    partial void OnadresChanged();
    #endregion
		
		public Sirket()
		{
			this._GelirGiders = new EntitySet<GelirGider>(new Action<GelirGider>(this.attach_GelirGiders), new Action<GelirGider>(this.detach_GelirGiders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isim", DbType="VarChar(100)")]
		public string isim
		{
			get
			{
				return this._isim;
			}
			set
			{
				if ((this._isim != value))
				{
					this.OnisimChanging(value);
					this.SendPropertyChanging();
					this._isim = value;
					this.SendPropertyChanged("isim");
					this.OnisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_kodu", DbType="Int")]
		public System.Nullable<int> sirket_kodu
		{
			get
			{
				return this._sirket_kodu;
			}
			set
			{
				if ((this._sirket_kodu != value))
				{
					this.Onsirket_koduChanging(value);
					this.SendPropertyChanging();
					this._sirket_kodu = value;
					this.SendPropertyChanged("sirket_kodu");
					this.Onsirket_koduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefon", DbType="VarChar(15)")]
		public string telefon
		{
			get
			{
				return this._telefon;
			}
			set
			{
				if ((this._telefon != value))
				{
					this.OntelefonChanging(value);
					this.SendPropertyChanging();
					this._telefon = value;
					this.SendPropertyChanged("telefon");
					this.OntelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(15)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eposta", DbType="VarChar(50)")]
		public string eposta
		{
			get
			{
				return this._eposta;
			}
			set
			{
				if ((this._eposta != value))
				{
					this.OnepostaChanging(value);
					this.SendPropertyChanging();
					this._eposta = value;
					this.SendPropertyChanged("eposta");
					this.OnepostaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yetkili_kisi", DbType="VarChar(50)")]
		public string yetkili_kisi
		{
			get
			{
				return this._yetkili_kisi;
			}
			set
			{
				if ((this._yetkili_kisi != value))
				{
					this.Onyetkili_kisiChanging(value);
					this.SendPropertyChanging();
					this._yetkili_kisi = value;
					this.SendPropertyChanged("yetkili_kisi");
					this.Onyetkili_kisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres", DbType="VarChar(150)")]
		public string adres
		{
			get
			{
				return this._adres;
			}
			set
			{
				if ((this._adres != value))
				{
					this.OnadresChanging(value);
					this.SendPropertyChanging();
					this._adres = value;
					this.SendPropertyChanged("adres");
					this.OnadresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sirket_GelirGider", Storage="_GelirGiders", ThisKey="ID", OtherKey="sirket_ID")]
		public EntitySet<GelirGider> GelirGiders
		{
			get
			{
				return this._GelirGiders;
			}
			set
			{
				this._GelirGiders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GelirGiders(GelirGider entity)
		{
			this.SendPropertyChanging();
			entity.Sirket = this;
		}
		
		private void detach_GelirGiders(GelirGider entity)
		{
			this.SendPropertyChanging();
			entity.Sirket = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GelirGider")]
	public partial class GelirGider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _sirket_ID;
		
		private System.Nullable<decimal> _gelir;
		
		private System.Nullable<decimal> _gider;
		
		private System.Nullable<System.DateTime> _tarih;
		
		private EntityRef<Sirket> _Sirket;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onsirket_IDChanging(System.Nullable<int> value);
    partial void Onsirket_IDChanged();
    partial void OngelirChanging(System.Nullable<decimal> value);
    partial void OngelirChanged();
    partial void OngiderChanging(System.Nullable<decimal> value);
    partial void OngiderChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    #endregion
		
		public GelirGider()
		{
			this._Sirket = default(EntityRef<Sirket>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sirket_ID", DbType="Int")]
		public System.Nullable<int> sirket_ID
		{
			get
			{
				return this._sirket_ID;
			}
			set
			{
				if ((this._sirket_ID != value))
				{
					if (this._Sirket.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsirket_IDChanging(value);
					this.SendPropertyChanging();
					this._sirket_ID = value;
					this.SendPropertyChanged("sirket_ID");
					this.Onsirket_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gelir", DbType="Money")]
		public System.Nullable<decimal> gelir
		{
			get
			{
				return this._gelir;
			}
			set
			{
				if ((this._gelir != value))
				{
					this.OngelirChanging(value);
					this.SendPropertyChanging();
					this._gelir = value;
					this.SendPropertyChanged("gelir");
					this.OngelirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gider", DbType="Money")]
		public System.Nullable<decimal> gider
		{
			get
			{
				return this._gider;
			}
			set
			{
				if ((this._gider != value))
				{
					this.OngiderChanging(value);
					this.SendPropertyChanging();
					this._gider = value;
					this.SendPropertyChanged("gider");
					this.OngiderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="Date")]
		public System.Nullable<System.DateTime> tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sirket_GelirGider", Storage="_Sirket", ThisKey="sirket_ID", OtherKey="ID", IsForeignKey=true)]
		public Sirket Sirket
		{
			get
			{
				return this._Sirket.Entity;
			}
			set
			{
				Sirket previousValue = this._Sirket.Entity;
				if (((previousValue != value) 
							|| (this._Sirket.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sirket.Entity = null;
						previousValue.GelirGiders.Remove(this);
					}
					this._Sirket.Entity = value;
					if ((value != null))
					{
						value.GelirGiders.Add(this);
						this._sirket_ID = value.ID;
					}
					else
					{
						this._sirket_ID = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sirket");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
